import numpy as np
from ase import Atoms

# ====================== Input Block ======================
input_parameters = {
    "cell_parameters": [
        [24.9534988404999992, 0.0, 0.0],  # a 벡터
        [0.0, 23.0512008667999984, 0.0],  # b 벡터
        [0.0, 0.0, 10.0],  # c 벡터
    ],
    "density_g_cm3": 0.98,  # 밀도 (g/cm³)
    "min_distance_OO": 2.3,  # 산소-산소 최소 거리 (Å)
    "output_filename": "POSCAR_H2O",  # 최종 구조 저장 경로
}
# ========================================================

def write_poscar(poscar_data, filename):
    """
    POSCAR 데이터를 저장합니다. 좌표를 원소별로 정렬하여 저장합니다.
    
    Parameters:
        poscar_data (dict): POSCAR 데이터
        filename (str): 저장할 파일 이름
    """
    cell = poscar_data['cell']
    symbols = poscar_data['elements']
    positions = poscar_data['positions']
    counts = poscar_data['counts']

    # 원소별로 좌표 정렬
    sorted_positions = []
    for symbol in symbols:
        sorted_positions.extend(poscar_data['symbol_positions'][symbol])
    
    # POSCAR 파일 작성
    with open(filename, 'w') as f:
        f.write(f"{poscar_data['comment']}\n")
        f.write(f"{poscar_data['scaling']:.16f}\n")
        for vector in cell:
            f.write("  " + "  ".join(f"{v:.16f}" for v in vector) + "\n")
        f.write("  " + "  ".join(symbols) + "\n")
        f.write("  " + "  ".join(map(str, counts)) + "\n")
        f.write(f"{poscar_data['coordinate_type']}\n")
        for pos in sorted_positions:
            f.write("  " + "  ".join(f"{v:>14.9f}" for v in pos) + "\n")

def pbc_distance(r1, r2, cell):
    """
    두 좌표 r1, r2 간의 PBC를 고려한 최소 거리 계산.
    
    Parameters:
        r1, r2 (array): 두 좌표 (Cartesian)
        cell (array): 셀 벡터
    
    Returns:
        float: PBC를 고려한 최소 거리
    """
    diff = r1 - r2
    cell_inv = np.linalg.inv(cell.T)  # 셀 벡터의 역행렬
    fractional_diff = np.dot(cell_inv, diff)  # Fractional 좌표로 변환
    fractional_diff -= np.round(fractional_diff)  # 최소 이미지 규칙 적용
    cartesian_diff = np.dot(cell.T, fractional_diff)  # 다시 Cartesian으로 변환
    return np.linalg.norm(cartesian_diff)

def generate_random_positions(cell, num_positions, min_distance, pbc=True):
    """
    셀 안에 랜덤으로 위치 생성, 최소 거리 조건 적용 (PBC 지원).
    
    Parameters:
        cell (array): 셀 벡터 (3x3)
        num_positions (int): 생성할 위치 개수
        min_distance (float): 최소 거리 조건
        pbc (bool): PBC 고려 여부
    
    Returns:
        np.array: 생성된 좌표 리스트
    """
    positions = []
    while len(positions) < num_positions:
        new_pos = np.random.uniform(0, 1, size=(3,)) @ cell  # 랜덤 Cartesian 좌표
        if all(
            pbc_distance(new_pos, pos, cell) >= min_distance
            for pos in positions
        ):
            positions.append(new_pos)
    return np.array(positions)

def create_water_structure_with_pbc(cell_parameters, density_g_cm3, min_distance_OO=2.8, output_filename="POSCAR"):
    """
    셀의 부피와 밀도를 사용하여 물 분자를 생성하고, PBC를 고려하여 배치한 후 POSCAR로 저장.
    
    Parameters:
        cell_parameters (list of list): 3x3 cell matrix (Å 단위)
        density_g_cm3 (float): 물의 밀도 (g/cm³, 예: 1 g/cm³)
        min_distance_OO (float): 산소-산소 최소 거리 (Å)
        output_filename (str): 저장할 파일 경로
    """
    # 물 분자의 초기 구조 정의 (O-H 거리: 0.96 Å)
    water = Atoms(
        symbols=["O", "H", "H"],
        positions=[[0, 0, 0], [0.96, 0, 0], [-0.32, 0.93, 0]],
    )

    # 셀의 부피 계산
    cell = np.array(cell_parameters)
    volume = np.abs(np.linalg.det(cell))  # Å³

    # 밀도를 g/cm³ -> g/Å³로 변환
    density_g_ang3 = density_g_cm3 / 1e24  # 1 cm³ = 10^24 Å³

    # 물 분자의 몰 질량과 밀도를 이용해 분자 수 계산
    molar_mass_h2o = 18.01528  # g/mol
    avogadro_number = 6.02214076e23
    mass_h2o = molar_mass_h2o / avogadro_number  # g
    num_molecules = int(volume * density_g_ang3 / mass_h2o)

    print(f"Cell volume: {volume:.2f} Å³")
    print(f"Estimated number of water molecules: {num_molecules}")

    # 산소 원자 랜덤 배치
    oxygen_positions = generate_random_positions(cell, num_molecules, min_distance_OO, pbc=True)

    # 물 분자 생성 및 회전 및 병합
    all_positions = []
    all_symbols = []
    symbol_positions = {symbol: [] for symbol in ["O", "H"]}
    for o_position in oxygen_positions:
        water_molecule = water.copy()

        # 랜덤 회전
        axis = np.random.rand(3)  # 랜덤 축
        angle = np.random.uniform(0, 360)  # 랜덤 각도
        water_molecule.rotate(angle, v=axis, center="COM")  # 회전 적용

        water_molecule.translate(o_position)  # 산소 위치로 이동
        for symbol, pos in zip(water_molecule.get_chemical_symbols(), water_molecule.positions):
            all_positions.append(pos)
            all_symbols.append(symbol)
            symbol_positions[symbol].append(pos)

    # POSCAR 데이터 구성
    poscar_data = {
        "comment": "Generated by ASE",
        "scaling": 1.0,
        "cell": cell,
        "elements": ["O", "H"],
        "counts": [all_symbols.count("O"), all_symbols.count("H")],
        "coordinate_type": "Cartesian",
        "positions": all_positions,
        "symbol_positions": symbol_positions,
    }

    # POSCAR 파일 저장
    write_poscar(poscar_data, output_filename)
    print(f"Generated structure saved to {output_filename}")

# --- 새 헬퍼: 축-각 회전행렬 (Rodrigues) ---
def _rand_rotation_matrix():
    axis = np.random.rand(3)
    axis /= np.linalg.norm(axis)
    theta = 2*np.pi*np.random.rand()
    K = np.array([[0, -axis[2], axis[1]],
                  [axis[2], 0, -axis[0]],
                  [-axis[1], axis[0], 0]])
    R = np.eye(3) + np.sin(theta)*K + (1-np.cos(theta))*(K @ K)
    return R

# --- 교체 1: pbc 거리 벡터화(역행렬 재사용) ---
def generate_random_positions_fast(cell, inv_cell, num_positions, min_distance):
    """
    셀 안에 O 원자 좌표를 랜덤 생성. 최소거리(O–O) 벡터화 검사, 파이썬 리스트 사용 최소화.
    실패 방지를 위해 시도 횟수 상한을 둡니다.
    """
    pos = np.empty((num_positions, 3), dtype=np.float64)
    k = 0
    tries = 0
    max_tries = max(1000, 50 * num_positions)  # 밀도/최소거리 조합에 따라 실패 대비

    while k < num_positions and tries < max_tries:
        tries += 1
        # 균일 분포 (fractional) → Cartesian
        new_cart = np.random.rand(3) @ cell

        if k == 0:
            pos[0] = new_cart
            k += 1
            continue

        diff = pos[:k] - new_cart                      # (k,3)
        diff_frac = diff @ inv_cell                    # Cartesian→fractional
        diff_frac -= np.round(diff_frac)               # 최소이미지
        diff_mic = diff_frac @ cell                    # fractional→Cartesian (MIC)
        if np.all(np.linalg.norm(diff_mic, axis=1) >= min_distance):
            pos[k] = new_cart
            k += 1

    if k < num_positions:
        print(f"[경고] 목표 {num_positions}개 중 {k}개만 배치되었습니다. "
              f"밀도 또는 min_distance를 낮추세요.")
        pos = pos[:k].copy()
    return pos

# --- 교체 2: 메인 생성 루틴(Atoms 회전/복사 제거, O 기준 회전) ---
def create_water_structure_with_pbc_fast(cell_parameters, density_g_cm3, min_distance_OO=2.8, output_filename="POSCAR"):
    cell = np.array(cell_parameters, dtype=np.float64)
    inv_cell = np.linalg.inv(cell)  # 1회만
    volume = abs(np.linalg.det(cell))  # Å^3

    density_g_ang3 = density_g_cm3 / 1e24
    molar_mass_h2o = 18.01528  # g/mol
    NA = 6.02214076e23
    mass_h2o = molar_mass_h2o / NA
    num_mol = int(volume * density_g_ang3 / mass_h2o)

    print(f"Cell volume: {volume:.2f} Å³")
    print(f"Estimated number of water molecules: {num_mol}")

    # O 좌표 생성(벡터화 검사)
    Opos = generate_random_positions_fast(cell, inv_cell, num_mol, min_distance_OO)

    # 물 분자 기하 (O를 원점으로 두고 회전 → O를 Opos로 이동)
    W0 = np.array([[0.0, 0.0, 0.0],
                   [0.96, 0.0, 0.0],
                   [-0.32, 0.93, 0.0]], dtype=np.float64)
    # 회전은 O 기준(즉, W0[0]이 원점)
    Hrel = W0[1:] - W0[0]  # (2,3)

    n = len(Opos)
    Hpos = np.empty((2*n, 3), dtype=np.float64)

    # 메모리 아끼기: 파이썬 객체 최소화, 순수 NumPy
    for i in range(n):
        R = _rand_rotation_matrix()
        Hr = (Hrel @ R.T)  # 회전된 H의 상대좌표
        Hpos[2*i]   = Opos[i] + Hr[0]
        Hpos[2*i+1] = Opos[i] + Hr[1]

    # POSCAR 바로 쓰기(원소 순서: O → H)
    with open(output_filename, "w") as f:
        f.write("Generated by ASE (fast)\n")
        f.write("1.0\n")
        for v in cell:
            f.write("  " + "  ".join(f"{x:.16f}" for x in v) + "\n")
        f.write("  O  H\n")
        f.write(f"  {n}  {2*n}\n")
        f.write("Cartesian\n")
        # O 먼저
        np.savetxt(f, Opos, fmt="%14.9f %14.9f %14.9f")
        # H 다음
        np.savetxt(f, Hpos, fmt="%14.9f %14.9f %14.9f")

    print(f"Generated structure saved to {output_filename}")

# Input Block의 파라미터 사용
create_water_structure_with_pbc_fast(
    cell_parameters=input_parameters["cell_parameters"],
    density_g_cm3=input_parameters["density_g_cm3"],
    min_distance_OO=input_parameters["min_distance_OO"],
    output_filename=input_parameters["output_filename"]
)

